// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mapa_do_bem_api.Repository;

namespace mapa_do_bem_api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211010062558_CreateDatabase")]
    partial class CreateDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ItemPontoDeColeta", b =>
                {
                    b.Property<int>("ItensDoacaoId")
                        .HasColumnType("int");

                    b.Property<int>("PontoDeColetaId")
                        .HasColumnType("int");

                    b.HasKey("ItensDoacaoId", "PontoDeColetaId");

                    b.HasIndex("PontoDeColetaId");

                    b.ToTable("ItemPontoDeColeta");
                });

            modelBuilder.Entity("mapa_do_bem_api.Model.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Produto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("Item");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Produto = "Alimento Não Perecível"
                        },
                        new
                        {
                            Id = 2,
                            Produto = "Alimento Preparado"
                        },
                        new
                        {
                            Id = 3,
                            Produto = "Produtos de Higiene Pessoal"
                        },
                        new
                        {
                            Id = 4,
                            Produto = "Roupas"
                        });
                });

            modelBuilder.Entity("mapa_do_bem_api.Model.PontoDeColeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DiasFuncionamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HorarioFuncionamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(8,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Numero")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("Id");

                    b.ToTable("PontoDeColeta");
                });

            modelBuilder.Entity("ItemPontoDeColeta", b =>
                {
                    b.HasOne("mapa_do_bem_api.Model.Item", null)
                        .WithMany()
                        .HasForeignKey("ItensDoacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mapa_do_bem_api.Model.PontoDeColeta", null)
                        .WithMany()
                        .HasForeignKey("PontoDeColetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
